/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonForm: typeof import('./src/components/business/CommonForm/index.vue')['default']
    Icon: typeof import('./src/components/common/Icon/index.vue')['default']
    InfiniteList: typeof import('./src/components/common/InfiniteList/index.vue')['default']
    Popup: typeof import('./src/components/common/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/common/Tree/index.vue')['default']
    TreeNode: typeof import('./src/components/common/Tree/TreeNode.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGrop: typeof import('vant/es')['CellGrop']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPopup: typeof import('vant/es')['Popup']
    VirtualList: typeof import('./src/components/common/VirtualList/index.vue')['default']
  }
}
